title:       "Green to Code"
description: "A blog about cloud, coding, security and more"
theme:       "just-the-docs"

url:         "https://green-to-code-blog.roadmaps.link"
baseurl:     ""    # No subfolder if using custom domain

search_enabled: true
color_scheme:   dark

aux_links:
  "GitHub Repo":
    - "https://github.com/scottiepowell/green-to-code-blog"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
